apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: capstonegoswamibucket
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: secret
  POSTGRESS_DB: capstonerds
  POSTGRESS_HOST: capstonerds.cvqgygxhhehg.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100
metadata:
  name: env-config
  
